groups:
  - name: ğŸŒŸ å…¬å…±æœåŠ¡
    services:
      - name: Blog
        app: VitePress æ—§åšå®¢
        url: https://wty9sky.github.io/blog_2023
        method: Docker
      - name: CV
        app: WebCV åœ¨çº¿ç®€å†
        url: https://wty9sky.github.io/wty_resume
        method: Vercel
  - name: ğŸŒŸ è‡ªå¼€æº&æ–‡æ¡£
    services:
      - name: SwordDesign
        app: SwordDesign ç»„ä»¶åº“æ–‡æ¡£
        url: https://blog.swdwiki.com/sword-design
        method: Github Action
      - name: SwordTools
        app: SwordTools å·¥å…·åº“æ–‡æ¡£
        url: https://blog.swdwiki.com/sword-tool
        method: Github Action
  - name: ğŸŒŸ AI & AIGC APP
    services:
      - name: AIGC
        app: Dify ç”Ÿæˆå¼ AI åº”ç”¨åˆ›æ–°å¼•æ“ 
        url: https://dify.swdwiki.com
        method: Docker
  - name: ğŸ‘¨â€ğŸ’» æ•ˆç‡å·¥å…·
    services:
      - name: Memos
        app: memos å¡ç‰‡ç¬”è®°
        url: https://memo.wty9sky.swdwiki.com
        method: Docker
      # - name: Archive
      #   app: ArchiveBox ç½‘é¡µå­˜æ¡£
      #   url: https://archive.swdwiki.com
      #   method: Docker
      - name: Password
        app: Warden å¯†ç ç®¡ç†
        url: https://pass.wty9sky.swdwiki.com
        method: Docker
  - name: ğŸ› ï¸ å¼€å‘ä¸è¿ç»´
    services:
      - name: Push
        app: Bark iOS æ¨é€æœåŠ¡
        url: https://bark.wty9sky.swdwiki.com
        method: Docker